from PySide6.QtCore import QSize

TMP_DIR = './tmp/'
BLURRED = '_blurred'

H_SIZE = 1000
V_SIZE = 615

SCROLLAREA_V_SIZE = 420

MAIN_SIZE = QSize(H_SIZE, V_SIZE)
BUTTON_V_SIZE = 22
MASK_BUTTON_H_SIZE = 80
ICON_V_SIZE = 18
ICON_H_SIZE = 18

GROUP_1_V_SIZE = 160

HI_RES = QSize(400, 400)

PIXMAP_MAX_SIZE = 300
PIXMAP_SCALE = QSize(PIXMAP_MAX_SIZE, PIXMAP_MAX_SIZE)

ACT_BTN_SIZE = QSize(160, 35)


